// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTaRbzc7eOHJW_sUuaGiGMgPeUg9Jj84o',
    appId: '1:770446391455:web:3034807040e202e7eb4aaa',
    messagingSenderId: '770446391455',
    projectId: 'pettounsi-d3d5e',
    authDomain: 'pettounsi-d3d5e.firebaseapp.com',
    storageBucket: 'pettounsi-d3d5e.firebasestorage.app',
    measurementId: 'G-D2QXEYKZNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjHrBGR57MgRmXau69DdKYjv2gzp0P2Dc',
    appId: '1:770446391455:android:4ce8fdc5ebb1d09eeb4aaa',
    messagingSenderId: '770446391455',
    projectId: 'pettounsi-d3d5e',
    storageBucket: 'pettounsi-d3d5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqC2IMYJDyytSueFYzzhp8hGHA19boVE',
    appId: '1:770446391455:ios:369c8ca5431f5ed4eb4aaa',
    messagingSenderId: '770446391455',
    projectId: 'pettounsi-d3d5e',
    storageBucket: 'pettounsi-d3d5e.firebasestorage.app',
    iosClientId: '770446391455-kk9m0urme7kfasldd89ahvn9t2viu9r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pettounsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqC2IMYJDyytSueFYzzhp8hGHA19boVE',
    appId: '1:770446391455:ios:369c8ca5431f5ed4eb4aaa',
    messagingSenderId: '770446391455',
    projectId: 'pettounsi-d3d5e',
    storageBucket: 'pettounsi-d3d5e.firebasestorage.app',
    iosClientId: '770446391455-kk9m0urme7kfasldd89ahvn9t2viu9r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pettounsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTaRbzc7eOHJW_sUuaGiGMgPeUg9Jj84o',
    appId: '1:770446391455:web:fd75c68c4fb789f2eb4aaa',
    messagingSenderId: '770446391455',
    projectId: 'pettounsi-d3d5e',
    authDomain: 'pettounsi-d3d5e.firebaseapp.com',
    storageBucket: 'pettounsi-d3d5e.firebasestorage.app',
    measurementId: 'G-QGZF4R6DV5',
  );
}
